# Generated by Django 4.1.2 on 2023-02-01 15:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductBrand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='عنوان')),
                ('url_title', models.CharField(max_length=120, verbose_name='عنوان در URL')),
                ('is_active', models.BooleanField(verbose_name='فعال / غیرفعال')),
                ('is_delete', models.BooleanField(verbose_name='حذف شده / حذف نشده')),
            ],
            options={
                'verbose_name': 'برند محصول',
                'verbose_name_plural': 'برندهای محصولات',
            },
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='عنوان')),
                ('url_title', models.CharField(max_length=120, verbose_name='عنوان در URL')),
                ('is_active', models.BooleanField(verbose_name='فعال / غیرفعال')),
                ('is_delete', models.BooleanField(verbose_name='حذف شده / حذف نشده')),
            ],
            options={
                'verbose_name': 'دسته بندی محصول',
                'verbose_name_plural': 'دسته بندی های محصولات',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='عنوان')),
                ('short_description', models.TextField(verbose_name='توضیحات کوتاه')),
                ('description', models.TextField(verbose_name='توضیحات')),
                ('production_date', models.PositiveBigIntegerField(verbose_name='سال ساخت')),
                ('production_country', models.CharField(max_length=150, verbose_name='کشور سازنده')),
                ('image', models.ImageField(upload_to='images/products', verbose_name='تصویر')),
                ('price', models.PositiveBigIntegerField(verbose_name='قیمت')),
                ('is_active', models.BooleanField(verbose_name='فعال / غیر فعال')),
                ('is_delete', models.BooleanField(verbose_name='حذف شده / حذف نشده')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='product_module.productbrand', verbose_name='برند')),
                ('category', models.ManyToManyField(to='product_module.productcategory', verbose_name='دسته بندی')),
            ],
            options={
                'verbose_name': 'محصول',
                'verbose_name_plural': 'محصولات',
            },
        ),
    ]
