# Generated by Django 4.1.6 on 2023-02-08 09:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('product_module', '0003_productgallery'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productgallery',
            options={'verbose_name': 'گالری تصویر محصول', 'verbose_name_plural': 'گالری تصاویر محصولات'},
        ),
        migrations.CreateModel(
            name='ProductComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(verbose_name='نظر کاربر')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت')),
                ('is_verify', models.BooleanField(default=False, verbose_name='تایید / عدم تایید توسط ادمین')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='product_module.product', verbose_name='محصول')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'نظر کاربر در مورد محصول',
                'verbose_name_plural': 'نظرات کاربران در مورد محصولات',
            },
        ),
    ]
