# Generated by Django 4.1.6 on 2023-03-29 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0006_product_discount_alter_product_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='in_stock',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='در انبار'),
        ),
    ]
