# Generated by Django 4.1.6 on 2023-02-28 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_module', '0002_supportserviceimage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SupportServiceImage',
        ),
    ]
