# Generated by Django 4.1.2 on 2022-11-17 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faq_module', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='faq',
            name='collapse',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='faq',
            name='heading',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
