# Generated by Django 4.1.2 on 2022-11-17 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faq_module', '0002_faq_collapse_faq_heading'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faq',
            name='collapse',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='faq',
            name='heading',
            field=models.CharField(max_length=200),
        ),
    ]
