# Generated by Django 4.1.2 on 2023-02-03 16:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('site_module', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='عنوان')),
                ('description', models.TextField(verbose_name='توضیحات')),
                ('button_title', models.CharField(max_length=20, verbose_name='عنوان لینک')),
                ('button_link', models.URLField(verbose_name='آدرس URL دکمه')),
                ('is_active', models.BooleanField(verbose_name='فعال / غیرفعال')),
            ],
            options={
                'verbose_name': 'جزییات سرویس ما',
                'verbose_name_plural': 'جزییات سرویس های ما',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='عنوان')),
                ('description', models.CharField(max_length=400, verbose_name='توضیحات')),
                ('is_active', models.BooleanField(verbose_name='فعال / غیرفعال')),
                ('icon', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='site_module.serviceicon', verbose_name='آیکن')),
            ],
            options={
                'verbose_name': 'سرویس ما',
                'verbose_name_plural': 'سرویس های ما',
            },
        ),
    ]
