# Generated by Django 4.1.6 on 2023-02-16 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basket_order_module', '0002_userbasketorderdetail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userbasketorder',
            name='is_paid',
            field=models.BooleanField(verbose_name='پرداخت شده / پرداخت نشده'),
        ),
    ]
