# Generated by Django 4.1.6 on 2023-02-21 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basket_order_module', '0003_alter_userbasketorder_is_paid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userbasketorder',
            name='is_paid',
            field=models.BooleanField(blank=True, null=True, verbose_name='پرداخت شده / پرداخت نشده'),
        ),
    ]
