# Generated by Django 4.1.6 on 2023-03-02 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basket_order_module', '0004_alter_userbasketorder_is_paid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userbasketorder',
            name='is_paid',
            field=models.BooleanField(verbose_name='پرداخت شده / پرداخت نشده'),
        ),
    ]
