# Generated by Django 4.1.6 on 2023-03-28 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basket_order_module', '0006_userbasketorderdetail_sell_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userbasketorderdetail',
            name='sell_price',
        ),
    ]
