# Generated by Django 4.1.6 on 2023-04-03 08:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('basket_order_module', '0009_rename_sell_price_userbasketorderdetail_single_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='userbasketorder',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ و زمان ایجاد'),
        ),
    ]
