# Generated by Django 4.1.6 on 2023-02-20 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wishlist_module', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userwishlist',
            name='commit_datetime',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='تاریخ و زمان ثبت'),
        ),
    ]
