# Generated by Django 4.1.6 on 2023-02-20 13:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0004_alter_productgallery_options_productcomment'),
        ('wishlist_module', '0003_alter_userwishlist_commit_datetime'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserWishListDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='product_module.product', verbose_name='محصول')),
                ('user_wish_list', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='wishlist_module.userwishlist', verbose_name='لیست غلاقه مندی کاربر')),
            ],
            options={
                'verbose_name': 'جزییات لیست علاقه مندی کاربر',
                'verbose_name_plural': 'جزییات لیست علاقه مندی های کاربران',
            },
        ),
    ]
