# Generated by Django 4.1.2 on 2022-11-16 14:22

from django.db import migrations, models
import utils.validators


class Migration(migrations.Migration):

    dependencies = [
        ('contact_module', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.EmailField(max_length=254, validators=[utils.validators.validate_email], verbose_name='ایمیل کاربر'),
        ),
    ]
