# Generated by Django 4.1.2 on 2022-11-23 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_module', '0002_blogcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogcategory',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='فعال / غیرفعال'),
            preserve_default=False,
        ),
    ]
