# Generated by Django 4.1.2 on 2022-11-23 12:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog_module', '0003_blogcategory_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='blog_module.blogcategory', verbose_name='دسته بندی'),
        ),
    ]
