# Generated by Django 4.1.2 on 2022-11-23 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_module', '0005_alter_blog_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='عنوان')),
                ('url_title', models.CharField(max_length=250, verbose_name='عنوان در URL')),
                ('is_active', models.BooleanField(verbose_name='فعال / غیرفعال')),
            ],
            options={
                'verbose_name': 'برچسب مقاله',
                'verbose_name_plural': 'برچسب های مقالات',
            },
        ),
        migrations.AlterModelOptions(
            name='blogcategory',
            options={'verbose_name': 'دسته بندی مقاله', 'verbose_name_plural': 'دسته بندی های مقالات'},
        ),
    ]
