# Generated by Django 4.1.2 on 2022-11-23 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_module', '0006_blogtag_alter_blogcategory_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='tag',
            field=models.ManyToManyField(blank=True, null=True, to='blog_module.blogtag', verbose_name='برچسب (تگ)'),
        ),
    ]
