# Generated by Django 4.1.2 on 2022-12-03 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_module', '0007_blog_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='tag',
            field=models.ManyToManyField(to='blog_module.blogtag', verbose_name='برچسب (تگ)'),
        ),
    ]
