# Generated by Django 4.1.2 on 2022-12-13 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_module', '0010_rename_verify_blogcomment_is_verify'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogcomment',
            name='is_verify',
            field=models.BooleanField(default=False, verbose_name='تایید / عدم تایید توسط ادمین'),
        ),
    ]
