# Generated by Django 4.1.6 on 2023-02-25 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=15, null=True, verbose_name='عنوان جزئی ( اختیاری )')),
                ('main_title', models.CharField(max_length=30, verbose_name='عنوان')),
                ('image', models.ImageField(upload_to='images/slider', verbose_name='تصویر')),
                ('link_title', models.CharField(max_length=15, verbose_name='عنوان لینک')),
                ('link', models.URLField(max_length=150, verbose_name='لینک')),
                ('is_active', models.BooleanField(verbose_name='فعال / غیرفعال')),
            ],
            options={
                'verbose_name': 'اسلایدر',
                'verbose_name_plural': 'اسلایدرها',
            },
        ),
    ]
