# Generated by Django 4.1.6 on 2023-02-28 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_module', '0005_supportservice_delete_suportservice'),
    ]

    operations = [
        migrations.AddField(
            model_name='supportservice',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='فعال / غیرفعال'),
        ),
    ]
