# Generated by Django 4.1.6 on 2023-03-01 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_module', '0006_supportservice_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sponser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام شرکت/سازمان')),
                ('image', models.ImageField(upload_to='images/sponsers', verbose_name='تصویر( لوگو ) شرکت')),
            ],
            options={
                'verbose_name': 'اسپانسر',
                'verbose_name_plural': 'اسپانسرها',
            },
        ),
    ]
