# Generated by Django 4.1.6 on 2023-03-01 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_module', '0007_sponser'),
    ]

    operations = [
        migrations.AddField(
            model_name='sponser',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='فعال / غیرفعال'),
            preserve_default=False,
        ),
    ]
