# Generated by Django 4.1.2 on 2022-11-13 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام مشتری')),
                ('major', models.CharField(max_length=100, verbose_name='تخصص')),
                ('image', models.ImageField(upload_to='images/about/customer', verbose_name='تصویر مشتری')),
                ('comment', models.TextField(verbose_name='نظر مشتری')),
            ],
            options={
                'verbose_name': 'نظر مشتری در مورد همکاری با ما',
                'verbose_name_plural': 'نظرات مشتری در مورد همکاری با ما',
            },
        ),
        migrations.CreateModel(
            name='ReasonChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='عنوان')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/about/reason-choice', verbose_name='تصویر')),
                ('description', models.TextField(verbose_name='توضیحات')),
            ],
            options={
                'verbose_name': 'دلیل انتخاب شرکت',
                'verbose_name_plural': 'دلایل انتخاب شرکت',
            },
        ),
        migrations.CreateModel(
            name='SpecializedField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='عنوان')),
                ('image', models.ImageField(upload_to='images/about/specialized', verbose_name='تصویر')),
                ('description', models.TextField(verbose_name='توضیحات')),
            ],
            options={
                'verbose_name': 'تخصص ما',
                'verbose_name_plural': 'تخصص های ما',
            },
        ),
    ]
