# Generated by Django 4.1.2 on 2022-11-14 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about_module', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customercomment',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='فعال / غیر فعال'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reasonchoice',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='فعال / غیر فعال'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='specializedfield',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='فعال / غیر فعال'),
            preserve_default=False,
        ),
    ]
