# Generated by Django 4.1.2 on 2022-11-14 16:35

import about_module.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about_module', '0003_customercomment_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customercomment',
            name='rate',
            field=models.PositiveIntegerField(validators=[about_module.models.validate_rate], verbose_name='امتیاز کاربر به ما'),
        ),
    ]
